### ISSUE TITLE
Add the ability for listeners to run with out local database

### ISSUE THREAD

**Issue by khuck** [cdwdirect/sos_flow#29]
Need to add a configuration option (argument, env. variable) to control the listener and aggregator databases.  For long-running applications (XGC, GENE, etc.) the shared filesystem is not an option, and the size of the databases gets too large (because of the flood of TAU data).  Currently, the XGC/GENE demo script deletes data, frame by frame, as it is consumed.  This should be managed by sosd, in case the analysis daemon fails for some reason.

- [ ] in-memory database option
- [ ] no database option
- [ ] constraints on database size
  - [ ] limit by size (bytes)
  - [ ] limit by # rows in tblvals
  - [ ] limit by # frames to keep

**Comment by cdwdirect** [comment]
Done!  Closing.
