### ISSUE TITLE
Add the ability to query multiple aggregators multithreaded

### ISSUE THREAD

**Issue by khuck** [cdwdirect/sos_flow#31]
When running with multiple aggregators, analysis queries should happen in parallel. This requires thread safety in the client analysis library.  Currently supported (?) in the chad_dev branch, needs integration into master.

Here is some example python code that would do multithreaded queries:
```python
def threadedQuery(a,sosPort,sql,index,tmp_results):
    print a,sosPort,sql,
    results, col_names = SOS.query(sql, a, sosPort)
    print "thread", str(index), "...done."
    tmp_results[index] += results

# Iterate over the running aggregators, and query them.
def queryAllAggregators(sql):
    global sosPort
    global aggregators
    global SOS
    allResults = None
    # set up our temporary results
    num_aggregators = len(aggregators)
    tmp_results = []
    for x in range(num_aggregators):
        tmp_results.append([])

    # Iterate over the aggregators, running the query against each one.
    # This could be done in parallel...
    index = 0
    threads = []
    for a in aggregators:
        process = Thread(target=threadedQuery, args=[a,sosPort,sql,index,tmp_results])
        process.start()
        threads.append(process)
        index = index + 1

    index = 0
    allResults = []
    for process in threads:
        process.join()
        allResults += tmp_results[index]
        index = index + 1

    col_names = [] # not used
    return allResults, col_names
```

Alternatively, the client API could possibly be extended to manage multiple aggregator connections. In addition to combining results, having a sort functionality would be ideal.  For example, submit a query, have it query 4 different aggregators, combine the results, then sort by column 4 descending then column 2 ascending...

**Comment by khuck** [comment]
Upon further consideration, we may want to look into managing this for the analysis layer, and hiding these details from the user.  Maybe 1 API call could query all of the servers and sort the results.

**Comment by cdwdirect** [comment]
Closed, multi-target query from a Python script's thread pool now works, with come caveats that I do not enforce order of responses, a thread can pick up the results of a query sent by another one.  This is not an issue in the real world because the query's are SIMD in nature and the threads are anonymous -- on returning they simply concatenate their results into a larger array for analysis.

Internal transparent multi-daemon query and reduction of feedback is a target for next major version number, at the earliest.
