### ISSUE TITLE
SOS client to write output as ADIOS

### ISSUE THREAD

**Issue by khuck** [cdwdirect/sos_flow#34]
(or this could be built into the aggregators)

Using ADIOS 1 and/or 2.  [https://github.com/ornladios/ADIOS2-Examples](https://github.com/ornladios/ADIOS2-Examples)
Algorithm:

- For each frame:
  - create group for values
  - select all values from frame
  - write out ADIOS step using current frame

Notes:
- need to manage global, local dimensions and offsets for cases with multiple aggregators.

**Comment by cdwdirect** [comment]
Is this something that should be baked into SOS daemons, or should it be a utility bundled in the SOS repo under examples?

It seems fairly complex/user-specific.

**Comment by khuck** [comment]
Ideally, it would be done in C code.  The prototype is written in Python.  But I agree it shouldn't be in the aggregator code because there can be multiple aggregators running.  This is the reason SOS configure looks for ADIOS, although that C implementation is not working at the moment, and the Python prototype is in a different repo for now.
