### ISSUE TITLE
Sqlite3 installed but ... missing

### ISSUE THREAD

**Issue by aurelemaheo** [cdwdirect/sos_flow#38]
I first installed sqlite3, then SOS dependencies and sos_flow.

sqlite3 is installed along with SOS dependencies:

[aurelem@pegasus sqlite3]$ pwd
/home/users/aurelem/sos/sqlite3
[aurelem@pegasus sqlite3]$ ls
bin  include  lib  share
[aurelem@pegasus sqlite3]$ 

I get the following error when building sos_flow:
EVPath Inst dir: /home/users/aurelem/tau/tau2/x86_64/sos/chaos/inst
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building on: Linux
CMake Error at cmake/FindSQLite3.cmake:93 (MESSAGE):
  Could not find Sqlite3
Call Stack (most recent call first):
  CMakeLists.txt:171 (find_package)

This bug happens on godzilla.nic.uoregon.edu and pegasus.nic.uoregon.edu machines, so far.

**Comment by aurelemaheo** [comment]
sos_flow builds correctly on delphi.

**Comment by khuck** [comment]
Did you pass -DSQLite3_DIR=/home/users/aurelem/sos/sqlite3 to the cmake command for sos?
There is also a version installed in /usr/local/packages/sqlite3/3.20.01

**Comment by aurelemaheo** [comment]
Yes I passed -DSQLite3_DIR option.

Here is what I get (on Pegasus):

[aurelem@pegasus sos]$ cd sqlite3/
[aurelem@pegasus sqlite3]$ pwd
/home/users/aurelem/sos/sqlite3
[aurelem@pegasus sqlite3]$ 
[aurelem@pegasus sqlite3]$ 
[aurelem@pegasus sqlite3]$ 
[aurelem@pegasus sqlite3]$ 
[aurelem@pegasus sqlite3]$ cd ..
[aurelem@pegasus sos]$ cd sos_flow/build-linux/
[aurelem@pegasus build-linux]$ ls
CMakeCache.txt  CMakeFiles
[aurelem@pegasus build-linux]$ rm -rf *
[aurelem@pegasus build-linux]$ 
[aurelem@pegasus build-linux]$ 
[aurelem@pegasus build-linux]$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/home/users/aurelem/sos/sos_flow/inst -DEVPath_DIR=/home/users/aurelem/sos/chaos/inst -SQLite3_DIR=/home/users/aurelem/sos/sqlite3 -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DSOS_CLOUD_SYNC_WITH_EVPATH=TRUE ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building on: Linux
CMake Error at cmake/FindSQLite3.cmake:93 (MESSAGE):
  Could not find Sqlite3
Call Stack (most recent call first):
  CMakeLists.txt:171 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/users/aurelem/sos/sos_flow/build-linux/CMakeFiles/CMakeOutput.log".
[aurelem@pegasus build-linux]$ 
[aurelem@pegasus build-linux]$ 
[aurelem@pegasus build-linux]$ 

And when I want to use sqlite3 in /usr/local/packages/sqlite3/3.20.01

[aurelem@pegasus build-linux]$ module avail sqlite3
[aurelem@pegasus build-linux]$ 
[aurelem@pegasus build-linux]$ 
[aurelem@pegasus build-linux]$ ls /usr/local/packages/sqlite3
3.20.01
[aurelem@pegasus build-linux]$ ls /usr/local/packages/sqlite3/3.20.01/
bin  include  lib  share
[aurelem@pegasus build-linux]$ pwd
/home/users/aurelem/sos/sos_flow/build-linux
[aurelem@pegasus build-linux]$ 
[aurelem@pegasus build-linux]$ 
[aurelem@pegasus build-linux]$ rm -rf *
[aurelem@pegasus build-linux]$ 
[aurelem@pegasus build-linux]$ 
[aurelem@pegasus build-linux]$ 
[aurelem@pegasus build-linux]$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/home/users/aurelem/sos/sos_flow/inst -DEVPath_DIR=/home/users/aurelem/sos/chaos/inst -SQLite3_DIR=/usr/local/packages/sqlite3/3.20.01 -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DSOS_CLOUD_SYNC_WITH_EVPATH=TRUE ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building on: Linux
CMake Error at cmake/FindSQLite3.cmake:93 (MESSAGE):
  Could not find Sqlite3
Call Stack (most recent call first):
  CMakeLists.txt:171 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/users/aurelem/sos/sos_flow/build-linux/CMakeFiles/CMakeOutput.log".

**Comment by aurelemaheo** [comment]
Are you able to reproduce this in Pegasus ? Here are the MPI and CMake versions I use:

[aurelem@pegasus build-linux]$ module list
Currently Loaded Modulefiles:
  1) mpi/mpich2-1.5_gcc-4.4   2) cmake/3.3.2

I use GCC 4.8.5

**Comment by khuck** [comment]
What is pegasus?

**Comment by aurelemaheo** [comment]
pegasus.nic.uoregon.edu

Can you test it ?

**Comment by aurelemaheo** [comment]
Sorry this was just a typo in the cmake command line: 
-SQLite3_DIR instead of -DSQLite3_DIR

It builds fine on both platforms with the given configuration.
