### ISSUE TITLE
Data Processing: Cache, Optimizations, No-DB Mode

### ISSUE THREAD

**Issue by cdwdirect** [cdwdirect/sos_flow#39]
- [x] UPDATE the 'current frame' value whenever stuff gets ingested with a query.

- [x] Query into cached values.
    - STEP1: Send everything
    - STEP2: Send only RegEx-matched values
    - STEP3: Send only RegEx-matched pubs
    - EVENTUALLY: Allow for N-depth cached values

- [x] Run-time options for database.
    - Store all history
    - Store most recent frame only
    - Store N-depth of frames
    - Store NOTHING in SQL
    - NEEDS: Run-time option per invocation of sosd.

**Comment by cdwdirect** [comment]
@khuck 

Currently in the **chad_dev** branch:

```
tblPubs.latest_frame
tblData.latest_frame
```
...BOTH are now updated as value snapshots come streaming in.

**NOTE**: `tblPubs.latest_frame` means exactly that, the last frame the database engine saw. Without some formal proofs, I would put an asterisk next to this next statement, but as far as I can see this is guaranteed to be the furthest frame, given current-version's communication patterns and serial-async-serial processing.  `tblData.latest_frame` is more useful (but more expensive to work with) because it will not always be the case that EVERY named value in a pub handle is updated with every `SOS_publish()` API call, which is what increments the pub handle's `frame` field, which is what is used to assign the `frame` of the value snapshots at their client origin. If you want to tag values with an explicit/user-defined "stepping" identifier, see the `SOS_pack_related()` API call.

![latest_frames](https://user-images.githubusercontent.com/10491306/36829960-4919b25e-1cd6-11e8-9a5a-4153171732ec.png)

_(Field names are truncated, not duplicated in the above screenshot.)_

**Comment by khuck** [comment]
To clarify, the "latest_frame" value is not _incremented_ but _updated_ (to the current frame value), right?

**Comment by cdwdirect** [comment]
Correct.

**Comment by cdwdirect** [comment]
Marking this closed since the database and cache are now working.  If rows need to be removed from the database, the query can be submitted by the analysis script, for now.

Deeper management/configurability (overall byte or row limit, page size optimizations, etc) of the SQL store is complex and should be revisited in a SOS 2.0 major version.
