### ISSUE TITLE
Call to SOS_init triggers a segmentation fault

### ISSUE THREAD

**Issue by aurelemaheo** [cdwdirect/sos_flow#40]
I built TAU with SOS on Delphi:
MPI implementation: mpi/mpich-3.1_gcc-4.9 

Version of TAU: up-to-date master branch.
Version of sos_flow: 02-13-18

I tried to run matmult code in TAU/examples/sos directory:

It runs well when TAU_SOS is set to 0.

[aurelem@delphi sos]$ export TAU_SOS=0
[aurelem@delphi sos]$ 
[aurelem@delphi sos]$ 
[aurelem@delphi sos]$ mpirun -np 4 ./matmult
MPI_Init_thread: provided = 3, MPI_THREAD_MULTIPLE=3
provided is MPI_THREAD_MULTIPLE
MPI_Init_thread: provided = 3, MPI_THREAD_MULTIPLE=3
provided is MPI_THREAD_MULTIPLE
MPI_Init_thread: provided = 3, MPI_THREAD_MULTIPLE=3
provided is MPI_THREAD_MULTIPLE
MPI_Init_thread: provided = 3, MPI_THREAD_MULTIPLE=3
provided is MPI_THREAD_MULTIPLE
Iteration 0 of 60 working...Iteration 0 of 60 done.
Iteration 1 of 60 working...Iteration 1 of 60 done.
Iteration 2 of 60 working...Iteration 2 of 60 done.
Iteration 3 of 60 working...Iteration 3 of 60 done.

When I set TAU_SOS to 1:

 
[aurelem@delphi sos]$ export TAU_SOS=1
[aurelem@delphi sos]$ 
[aurelem@delphi sos]$ 
[aurelem@delphi sos]$ mpirun -np 4 ./matmult

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 53229 RUNNING AT delphi
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
[aurelem@delphi sos]$ 
[aurelem@delphi sos]$ mpirun -np 4 ./matmult

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 53249 RUNNING AT delphi
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

When I try to debug it:

[aurelem@delphi sos]$ gdb ./matmult
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-100.el7_4.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /storage/users/aurelem/tau/tau2_sos/examples/sos/matmult...done.
(gdb) r
Starting program: /storage/users/aurelem/tau/tau2_sos/examples/sos/./matmult 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: File "/storage/packages/gcc/4.9.3/lib64/libstdc++.so.6.0.20-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".
To enable execution of this file add
	add-auto-load-safe-path /storage/packages/gcc/4.9.3/lib64/libstdc++.so.6.0.20-gdb.py
line to your configuration file "/home/users/aurelem/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/users/aurelem/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"

Program received signal SIGSEGV, Segmentation fault.
__GI_____strtol_l_internal (nptr=0x0, endptr=endptr@entry=0x0, base=base@entry=10, group=group@entry=0, loc=0x7ffff64c1060 <_nl_global_locale>) at ../stdlib/strtol_l.c:298
298	  while (ISSPACE (*s))
Missing separate debuginfos, use: debuginfo-install zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  __GI_____strtol_l_internal (nptr=0x0, endptr=endptr@entry=0x0, base=base@entry=10, group=group@entry=0, loc=0x7ffff64c1060 <_nl_global_locale>) at ../stdlib/strtol_l.c:298
#1  0x00007ffff613dcf2 in __GI_strtol (nptr=<optimized out>, endptr=endptr@entry=0x0, base=base@entry=10) at ../stdlib/strtol.c:109
#2  0x00007ffff6f1a9be in atoi (__nptr=<optimized out>) at /usr/include/stdlib.h:280
#3  SOS_init_existing_runtime (argc=argc@entry=0x7fffffffdab4, argv=argv@entry=0x7fffffffdab8, sos_runtime=sos_runtime@entry=0x8304a8 <_runtime>, sos_options_ptr=<optimized out>, role=role@entry=SOS_ROLE_CLIENT, 
    receives=receives@entry=SOS_RECEIVES_NO_FEEDBACK, handler=0x0) at /home/users/aurelem/tau/tau2_sos/x86_64/sos/sos_flow/src/sos.c:329
#4  0x00007ffff6f1af21 in SOS_init (argc=0x7fffffffdab4, argv=0x7fffffffdab8, sos_runtime=0x8304a8 <_runtime>, role=SOS_ROLE_CLIENT, receives=SOS_RECEIVES_NO_FEEDBACK, handler=0x0) at /home/users/aurelem/tau/tau2_sos/x86_64/sos/sos_flow/src/sos.c:148
#5  0x000000000046f5a4 in TAU_SOS_init (argc=argc@entry=0x7fffffffdbbc, argv=argv@entry=0x7fffffffdbb0, threaded=threaded@entry=true) at TauSOS.cpp:389
#6  0x000000000042f0cd in MPI_Init_thread (argc=0x7fffffffdbbc, argv=0x7fffffffdbb0, required=<optimized out>, provided=0x7c9fd8 <provided>) at TauMpi.c:1958
#7  0x000000000042c002 in main (argc=1, argv=0x858550) at matmult.c:163
(gdb) 

There must be a wrong value passed to SOS_init().

**Comment by khuck** [comment]
This commonly happens when an SOS environment variable is not set.  This should be fixed in a branch (not master), but we'll be merging soon.
