### ISSUE TITLE
Building ssos_python.so fails for all compilers except gcc

### ISSUE THREAD

**Issue by khuck** [cdwdirect/sos_flow#44]
CFFI only supports gcc.  It adds compiler options that are only compatible with gcc (-fwrapv for example).  However, we can work around that.  All of SOS can be built with another compiler (PGI, say), and then the python library can be built with gcc (seems to be ABI compatible - as long as the PGI compiler uses the same GNU stdlibc).  But we have to figure out the magic CMake sauce to change the compiler before the build_... script is called.  Just setting CMAKE_C_COMPILER before adding the custom target doesn't seem to be sufficient.

**Comment by cdwdirect** [comment]
Looks like a relatively clean solution given here: https://stackoverflow.com/a/44312160

**Comment by khuck** [comment]
Ha... I had read the same article and tried the same thing (or similar) and it didn't work on titan.  Not a high priority for now.  We can build SOS with GCC and copy the ssos_python.so to the PGI installation, as long as the GCC libstdc is the same.

**Comment by khuck** [comment]
Fixed with 9ef3c26c108ef8ead6bea20db880233e717b1a58.
